name: Default Process
description: Default Action Process For All Jobs

runs: 
  using: "composite"
  steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Python Cache
      uses: actions/cache@v3
      id: cache
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: pip-

    - name: Install Robot Dependencies
      shell: bash
      run: |
        pip install -r requirements.txt

        echo Instalando o Node.js
        curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        
    - name: Restaurar Cache do npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Instalar Dependências do Node.js
      shell: bash
      run: npm install

    - name: Salvar Cache do npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}